In [1]:

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from keras import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

print('import done')

import done


In [2]:

iris_data = load_iris() 
print(iris_data.data[:5])


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [4]:

x = iris_data.data
y_ = iris_data.target.reshape(-1, 1)

encoder = OneHotEncoder(sparse=False)
y = encoder.fit_transform(y_)

train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.20)


model = Sequential()

model.add(Dense(10, input_shape=(4,), activation='relu', name='fc1'))
model.add(Dense(10, activation='relu', name='fc2'))
model.add(Dense(3, activation='softmax', name='output'))

optimizer = Adam(learning_rate=0.001)
model.compile(optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

print('Neural Network Model Summary: ')
print(model.summary())

model.fit(train_x, train_y, verbose=2, batch_size=5, epochs=200)

Neural Network Model Summary: 


C:\Users\Trupti\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
C:\Users\Trupti\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ fc1 (Dense)                     │ (None, 10)             │            50 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ fc2 (Dense)                     │ (None, 10)             │           110 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ output (Dense)                  │ (None, 3)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 193 (772.00 B)

 Trainable params: 193 (772.00 B)

 Non-trainable params: 0 (0.00 B)

None
Epoch 1/200
24/24 - 2s - 91ms/step - accuracy: 0.3000 - loss: 1.3707
Epoch 2/200
24/24 - 0s - 3ms/step - accuracy: 0.3000 - loss: 1.2143
Epoch 3/200
24/24 - 0s - 2ms/step - accuracy: 0.3167 - loss: 1.1289
Epoch 4/200
24/24 - 0s - 2ms/step - accuracy: 0.3750 - loss: 1.0712
Epoch 5/200
24/24 - 0s - 2ms/step - accuracy: 0.3667 - loss: 1.0265
Epoch 6/200
24/24 - 0s - 2ms/step - accuracy: 0.3750 - loss: 0.9792
Epoch 7/200
24/24 - 0s - 2ms/step - accuracy: 0.4833 - loss: 0.9346
Epoch 8/200
24/24 - 0s - 2ms/step - accuracy: 0.6583 - loss: 0.8990
Epoch 9/200
24/24 - 0s - 3ms/step - accuracy: 0.6667 - loss: 0.8633
Epoch 10/200
24/24 - 0s - 3ms/step - accuracy: 0.6667 - loss: 0.8271
Epoch 11/200
24/24 - 0s - 3ms/step - accuracy: 0.6667 - loss: 0.7894
Epoch 12/200
24/24 - 0s - 3ms/step - accuracy: 0.6667 - loss: 0.7489
Epoch 13/200
24/24 - 0s - 3ms/step - accuracy: 0.6667 - loss: 0.7088
Epoch 14/200
24/24 - 0s - 3ms/step - accuracy: 0.6667 - loss: 0.6701
Epoch 15/200
24/24 - 0s - 2ms/step - 

In [5]:
# Test on unseen data
results = model.evaluate(test_x, test_y)

print('Final test set loss: {:4f}'.format(results[0]))
print('Final test set accuracy: {:4f}'.format(results[1]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 251ms/step - accuracy: 1.0000 - loss: 0.0236
Final test set loss: 0.023632
Final test set accuracy: 1.000000
